### PR TITLE
Simplify code and add comments

### PR DESCRIPTION
**Pull request by bpbond**
The code was doing work it didn't have to, at least as far as I could see. This PR simplifies things and I think fixes the bad-sort issue in #205

### CODE REVIEW

**Comment by stephpenn1** [comment]
Fixes the sorting but it looks like I have NAs now and some duplicates happening in the loop, looking into it!
image

**Comment by bpbond** [comment]
Hmm what's wrong with that graph? 😕  anyway, I have plane time tomorrow, great time to look into a problem if I understand -- lmk

**Comment by stephpenn1** [comment]
NA time stamps at the end (far right!)

**Comment by stephpenn1** [comment]
image

**Comment by bpbond** [comment]
Oh got it, OK. Well again I have a lot of quality airplane tomorrow so feel free to toss over to me :)

Thanks again for being willing to meet late today!

**Review by stephpenn1 — APPROVED** [review]
The NA issue is resolved now!

**Pull request merged**
