### PR TITLE
Create flmd-generator.R

### PR DESCRIPTION
**Pull request by bpbond**
Draft until feedback on the google sheet from @stephpenn1

### CODE REVIEW

**Comment by stephpenn1** [comment]
Google sheet looks great, running script on my computer next

**Comment by stephpenn1** [comment]
```

**Comment by stephpenn1** [comment]
```
results <- tibble(file = list.files(path = "./data/L1/",
                                    recursive = TRUE,
                                    full.names = TRUE),
                  sort = seq_along(file),
                  File_Path = gsub("^\\./data/L1//", "", dirname(file)),
                  File_Name = basename(file)
)
```

If I understand this correctly, does this assume there are data files present in the workflow folders? I don't have any currently in the L1 folder, but have a folder downloaded from the HPC. Can I just switch that directory?

**Comment by bpbond** [comment]
Correct. Yes, you can switch the `path` parameter to wherever you have the L1 data.

**Comment by stephpenn1** [comment]
This looks great!

**Review by stephpenn1 — APPROVED** [review]
Thanks again

**Pull request merged**
